# Generated by Django 4.1.2 on 2022-12-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.post')),
            ],
        ),
    ]
