# Generated by Django 4.1.2 on 2022-12-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='bookmarkers',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_posts', to='application.userprofile'),
        ),
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='application.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.userprofile'),
        ),
    ]
