# Generated by Django 4.1.2 on 2022-12-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_comment_text_alter_post_image_space_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='spaces',
        ),
        migrations.AddField(
            model_name='post',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='application.space'),
        ),
    ]
