# Generated by Django 4.1.2 on 2022-12-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_post_spaces_post_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
