# Generated by Django 4.1.2 on 2022-12-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_post_created_at'),
    ]

    operations = [
    ]
