# Generated by Django 4.1.2 on 2022-12-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20221227_1702'),
    ]

    operations = [
    ]
